---
title: "Kartoffelsalat 1"
format: html
editor: visual
---

## Kartoffelsalat 1

**Zutaten:**

-   Kartoffeln

-   Eier

-   Möhren und Erbsen aus der Dose

-   Saure Gurken

-   Zwiebeln

-   Salz, Pfeffer

-   Miracal Whip (light reicht auch)

-   Optional: Fleischwurst

**Zubereitung:**

1.  Alle festen Zutaten außer die Erbsen klein schneiden. Feste Zutaten vermischen.
2.  Für die Sauce Miracel Whip, einen Teil des Gurkenwassers mit Salz und Pfeffer vermischen.
3.  Sauce unterheben und den Salat ziehen lassen.

## Kartoffelsalat 2

**Zutaten:**

-   Ein Sack Kartoffeln

-   Ein Glas Saure Gurken

-   Mayo

-   Eine Zwiebel

-   Salz und Pfeffer

**Zubereitung:**

1.  Kartoffeln kochen und hinterher pellen.
2.  Saure Gurken und Zwiebeln in kleine Stücke schneiden. Achtung: Gurkenwasser behalten!
3.  Kartoffeln in Scheiben schneiden und in eine Schüssel tun. Gurken und Zwiebeln dazu tun.
4.  Gurkenwasser auf die Kartoffeln gießen. Über Nacht ziehen lassen.
5.  Am nächsten Tag Mayo unterheben und mit Salz und Pfeffer abschmecken.

## Möhren-Apfel-Salat

**Zutaten:**

-   Möhren

-   Äpfel

-   Zitrone

-   Neutrales Öl, z.B. Rapsöl

-   Salz, Pfeffer und Zucker

**Zubereitung:**

1.  Möhren und Äpfel in der Küchenmaschine einzeln zerkleinern. Danach vermischen.
2.  Zitrone auspressen.
3.  Zitronensaft, Öl und Gewürze vermischen und dann in die Möhren-Apfel-Mischung rühren.
4.  Kurz durchziehen lassen.

## Gemüse-Zwiebel-Aufstrich

**Zutaten:**

-   30 g Zwiebeln

-   60 g Karotte

-   20 g Sellerie

-   30 g Lauch

-   100 g Margarine

-   Salz, Pfeffer, evtl. Knoblauchzehen

**Zubereitung:**

1.  Gemüse in feine Würfel schneiden und in der Margarine dünsten. Mit Salz und Pfeffer würzen.
2.  Masse in Schälchen oder kleine Marmeladengläser füllen und eine Nacht in den Kühlschrank stellen.
