---
title: "Kartoffelkuchen"
format: html
editor: visual
---

## Kartoffelkuchen

**Für den Teig:**

-   500 g Mehl

-   500 g Kartoffeln

-   500 g Honig

-   250 g Zucker

-   2-4 Eier

-   2 TL Zimt

-   2 TL gemahlene Nelken

-   2 gehäufte TL Natron

-   100-120 g Butter

-   Kakao (nach Geschmack)

-   Nüsse gehackt (Walnüsse oder Mandeln)

Zum Verzieren: Vollmilchschokolade (oder evtl. einen Teil zartbitter, je nachdem, wie süß man es mag) und schöne Walnusshälften

**Zubereitung:**

1.  Kartoffeln kochen und abkühlen lassen.
2.  Kartoffeln mit der Kartoffelpresse zerdrücken.
3.  Honig und Zucker verrühren, danach die Butter hinzufügen und mischen.
4.  Mehl, Kakao, Zimt, Nelke und Natron vermischen.
5.  Restliche Zutaten hinzufügen und einen Teig herstellen.
6.  Teig auf einem gefetteten Backblech glatt streichen.
7.  Auf 175° C 30 Minuten lang backen.
8.  Nach dem Abkühlen in quadratische Stücke schneiden.
9.  Die Oberseite mit geschmolzener Schokolade überziehen, am besten sie fließt seitlich noch ein bisschen herunter. Dann in die Mitte die Walnusshälfte setzen.
