---
title: "Schokokuchen"
format: html
editor: visual
---

## Schokokuchen

**Zutaten**:

-   Olivenöl für die Form

-   6 EL Kakaopulver

-   1 Vanilleschote (herausgeschabtes Mark)

-   1 Prise Salz

-   3 Eier

-   225 g Kristallzucker

-   180 ml Traubenkernöl (ersatzweise Olivenöl)

-   200 g sehr fein geriebene Mandeln

-   1/2 TL Backpulver

**Zubereitung**:

1.  Den Ofen auf 175 Grad bei Ober-/ Unterhitze vorheizen. Backform mit etwas Olivenöl auspinseln.
2.  In einem Topf 200 ml Wasser auf­kochen. Kakaopulver mit Vanille­mark und der Prise Salz hineingeben und zu einer geschmeidigen Masse verrühren. Kakaomasse vom Herd nehmen und auskühlen lassen.
3.  Inzwischen Eier und Zucker in der Rührmaschine sehr luftig aufschlagen (ca. 10 Minuten). Geschwindigkeit auf mittlere Stufe reduzieren und das Traubenkernöl in einem dünnen Strahl langsam einfließen lassen, sodass eine homo­gene Masse entsteht (wie bei der Herstellung von Mayonnaise). Dann mit einem Gummispachtel die ausgekühlte Kakaomasse unterheben.
4.  Geriebene Mandeln mit dem Backpulver mischen und durch ein gröberes Sieb in die Masse streichen, ebenfalls vorsichtig unterheben.
5.  Teig in die Form geben und im Ofen 45 Minuten backen. Mit einem Holzspieß eine Probe machen (es darf nichts mehr am Spieß hängen bleiben). Kuchen in der Form bei Zimmertemperatur auskühlen lassen.

**Quelle:** <https://sz-magazin.sueddeutsche.de/das-kochquartett/rezept-schokoladenkuchen-erdbeeren-laktose-gluten-91450>
