---
title: "Torte"
format: html
editor: visual
---

## Torte

… für eine Füllung nach Belieben :)

**Für den Teig:**

-   4 Eier

-   3 EL kaltes Wasser

-   1 Prise Salz

-   150 g Zucker

-   1 Päckchen Vanillezucker

-   120 g Diamantmehl

-   40 g Speisestärke

-   ½ gehäufter TL Backpulver

**Zubereitung:**

1.  Die Springform (Durchmesser 24 cm) vorbereiten: Backpulver in Form des Bodens schneiden. Den Boden einbuttern. Die Form schließen und das zugeschnittene Backpapier auf den Boden drücken.
2.  Die Eiweiße, das Wasser und das Salz steif schlagen (Mit dem Handrührgerät wird es besser als mit der Küchenmaschine, aber vielleicht ist deine Küchenmaschine auch besser).
3.  Zucker und Vanillezucker in einer neuen Schüssel vermischen.
4.  Dann immer abwechselnd ein Ei und ein bisschen von der Zuckermischung unter den Teig schlagen. Dabei darauf achten, dass das ganze schön aufgeschlagen bleibt und nicht wieder flüssig wird. Wenn alles zusammengefügt ist, sollte man mit dem Teig eine acht auf den Teig malen können und diese sollte stehen bleiben.
5.  In einer leeren Schüssel das Mehl, die Speisestärke und das Backpulver vermischen. Dann nach und nach über die Eiermasse sieben und zwischendurch immer unterheben (nicht schlagen, sonst fällt der Teig wieder zusammen).
6.  Den Teig in die Springform füllen.
7.  Im vorgeheizten Backofen auf 175° C Ober- und Unterhitze 45 Minuten lang backen.
